# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 90s
    servlet:
        context-path: /

spring:
    application:
        name: meeting-data
    # 环境 dev|test|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            servlet:
                max-file-size: 100MB
                max-request-size: 100MB
                enabled: true
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 11.111.111.11 #ip,假的
        port: 6379
        password: # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
    mvc:
        throw-exception-if-no-handler-found: true
        static-path-pattern: /static/**
    resources:
        static-locations: classpath:static/,file:static/
    jpa:
        database: mysql
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update

#mybatis
mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.meeting.modules.*.entity
    global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 2
        #驼峰下划线转换
        db-column-underline: true
        #刷新mapper 调试神器
        refresh-mapper: true
        #数据库大写下划线转换
        #capital-mode: true
        #序列接口实现类配置
        #key-generator: com.baomidou.springboot.xxx
        #逻辑删除配置
        logic-delete-value: -1
        logic-not-delete-value: 0
        #自定义填充策略接口实现
        #meta-object-handler: com.baomidou.springboot.xxx
        #自定义SQL注入器
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true

logging:
    level:
        org:
            springframework:
                web: info42
        com:
            meeting:
                modules: debug

#===================================oss相关配置======================================
ossclient:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAISQTwsxrYKXM7
    accessKeySecret: O33wSUewP4cXFdbhnRlfJ3JNQaQk3Z
    bucketName: xiaomo-oss
    fileHost: image


#=================================微信相关====================================!
#公众号
wxpay:
  appid: wxmag045zy43s0o5g7
  appsecret: 06o31c64x6c70eo8vb97213j700wyf34
#微信商户平台
  mer_id: 3176078688
  key: R98372x40pX6o0236D7bCP127SS1f733
  callback: gds.ngrok.xiaomiqiu.cn/api/v1/wechat/order/callback
  #wxpay.callback=http://api.xdclass.net

#微信开放平台配置<登录>
wxopen:
  appid: wx2a6cf9373f278ed2
  appsecret: cbc3fbc52ff1977ca25e4298bffbc07c
  #重定向url
  redirect_url: gds.ngrok.xiaomiqiu.cn/api/v1/wechat/user/callback

